### create Account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 20000
}

### delete Account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000"
}

### 계좌 조회
GET http://localhost:8080/account?user_id=1
Content-Type: application/json